GestaoFinancas/GestaoFinancasWeb/Controllers/CategoriasController.cs
using Microsoft.AspNetCore.Mvc;
using GestaoFinancasWeb.Models;
using System.Linq;
using Microsoft.AspNetCore.Http; 

namespace GestaoFinancasWeb.Controllers;

public class CategoriasController : Controller
{
    // GET: Listar Categorias
    public IActionResult Index()
    {
        if (HttpContext.Session.GetString("Utilizador") == null) return RedirectToAction("Login", "Conta");
        var lista = Persistencia.CarregarCategorias();
        return View(lista);
    }

    // GET: Criar
    public IActionResult Criar()
    {
        if (HttpContext.Session.GetString("Utilizador") == null) return RedirectToAction("Login", "Conta");
        return View();
    }

    // POST: Criar
    [HttpPost]
    public IActionResult Criar(Categoria novaCat)
    {
        if (ModelState.IsValid)
        {
            var lista = Persistencia.CarregarCategorias();
            // Gera ID automático
            novaCat.Id = lista.Count > 0 ? lista.Max(c => c.Id) + 1 : 1;
            
            lista.Add(novaCat);
            Persistencia.GuardarCategorias(lista);
            return RedirectToAction("Index");
        }
        return View(novaCat);
    }

    // NOVO: ELIMINA (Pergunta)
    public IActionResult Eliminar(int id)
    {
        if (HttpContext.Session.GetString("Utilizador") == null) return RedirectToAction("Login", "Conta");

        var lista = Persistencia.CarregarCategorias();
        var cat = lista.FirstOrDefault(c => c.Id == id);
        
        if (cat == null) return NotFound();
        
        return View(cat);
    }

    // ELIMINAR (Confirma) ---
    [HttpPost, ActionName("Eliminar")]
    public IActionResult ConfirmarEliminar(int id)
    {
        var lista = Persistencia.CarregarCategorias();
        var cat = lista.FirstOrDefault(c => c.Id == id);

        if (cat != null)
        {
            lista.Remove(cat);
            Persistencia.GuardarCategorias(lista);
        }
        return RedirectToAction("Index");
    }
}

GestaoFinancas/GestaoFinancasWeb/Controllers/ContaController.cs
using Microsoft.AspNetCore.Mvc;
using GestaoFinancasWeb.Models;
using System.Linq;
using Microsoft.AspNetCore.Http; 

namespace GestaoFinancasWeb.Controllers
{
    public class ContaController : Controller
    {
        // GET: Login (Mostra o formulário)
        public IActionResult Login()
        {
            return View();
        }

        // POST: Login (Verifica a password)
        [HttpPost]
        public IActionResult Login(string username, string password)
        {
            var utilizadores = Persistencia.CarregarUtilizadores();
            
            // Procura se existe alguém com este nome e password
            var user = utilizadores.FirstOrDefault(u => u.Username == username && u.Password == password);

            if (user != null)
            {
                // SUCESSO: Cria a sessão
                HttpContext.Session.SetString("Utilizador", user.Username);
                // Opcional: Guardar o ID ou Perfil na sessão se precisares no futuro
                HttpContext.Session.SetString("Perfil", user.Perfil);
                
                return RedirectToAction("Index", "Home"); 
            }

            // ERRO:
            ViewBag.Erro = "Nome ou Password incorretos!";
            return View();
        }

        // GET: Registar
        public IActionResult Registar()
        {
            return View();
        }

        // POST: Registar (Grava no ficheiro)
        [HttpPost]
        public IActionResult Registar(Utilizador novoUser)
        {
            var utilizadores = Persistencia.CarregarUtilizadores();

            // Verifica se já há username
            if (utilizadores.Any(u => u.Username == novoUser.Username))
            {
                ViewBag.Erro = "Esse utilizador já existe!";
                return View(novoUser);
            }

            // Gera ID Automático ---
            novoUser.Id = utilizadores.Count > 0 ? utilizadores.Max(u => u.Id) + 1 : 1;
            
            // Define Perfil Padrão ---
            novoUser.Perfil = "Normal";

            // Grava
            utilizadores.Add(novoUser);
            Persistencia.GuardarUtilizadores(utilizadores);

            return RedirectToAction("Login");
        }

        // Logout
        public IActionResult Logout()
        {
            HttpContext.Session.Clear(); 
            return RedirectToAction("Login");
        }
    }
}

GestaoFinancas/GestaoFinancasWeb/Controllers/DespesasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using GestaoFinancasWeb.Models;
using Microsoft.AspNetCore.Http;

namespace GestaoFinancasWeb.Controllers
{
    public class DespesasController : Controller
    {
        private static List<Despesa> listaDespesas = Persistencia.CarregarDespesas();

        // LISTAR (Protegido)
        public IActionResult Index()
        {
            // entrar
            if (HttpContext.Session.GetString("Utilizador") == null)
            {
                return RedirectToAction("Login", "Conta");
            }

            listaDespesas = Persistencia.CarregarDespesas();
            return View(listaDespesas);
        }

        // CRIAR 
        public IActionResult Criar()
        {
            // Carrega categorias para o dropdown
            ViewBag.ListaCategorias = Persistencia.CarregarCategorias();
            return View();
        }

        // CRIAR (Guardar)
        [HttpPost]
        public IActionResult Criar(Despesa novaDespesa)
        {
            if (ModelState.IsValid)
            {
                novaDespesa.Identificacao = listaDespesas.Count > 0 ? listaDespesas.Max(d => d.Identificacao) + 1 : 1;
                listaDespesas.Add(novaDespesa);
                Persistencia.GuardarDespesas(listaDespesas);
                return RedirectToAction("Index");
            }
            
            // Recarrega categorias se houver erro
            ViewBag.ListaCategorias = Persistencia.CarregarCategorias();
            return View(novaDespesa);
        }

        // Eliminar
        public IActionResult Eliminar(int id)
        {
            var despesa = listaDespesas.FirstOrDefault(d => d.Identificacao == id);
            if (despesa == null) return NotFound();
            return View(despesa);
        }

        // Confirma no eliminar
        [HttpPost, ActionName("Eliminar")]
        public IActionResult ConfirmarEliminar(int id)
        {
            var despesa = listaDespesas.FirstOrDefault(d => d.Identificacao == id);
            if (despesa != null)
            {
                listaDespesas.Remove(despesa);
                Persistencia.GuardarDespesas(listaDespesas);
            }
            return RedirectToAction("Index");
        }

        // Editar
        public IActionResult Editar(int id)
        {
            var despesa = listaDespesas.FirstOrDefault(d => d.Identificacao == id);
            if (despesa == null) return NotFound();

            // Carrega categorias para o dropdown
            ViewBag.ListaCategorias = Persistencia.CarregarCategorias();
            return View(despesa);
        }

        // EDITAR (Guardar)
        [HttpPost]
        public IActionResult Editar(Despesa despesaAtualizada)
        {
            var despesaAntiga = listaDespesas.FirstOrDefault(d => d.Identificacao == despesaAtualizada.Identificacao);
            if (despesaAntiga != null)
            {
                despesaAntiga.Descricao = despesaAtualizada.Descricao;
                despesaAntiga.Valor = despesaAtualizada.Valor;
                despesaAntiga.CategoriaNome = despesaAtualizada.CategoriaNome;
                despesaAntiga.Data = despesaAtualizada.Data;
                
                Persistencia.GuardarDespesas(listaDespesas);
                return RedirectToAction("Index");
            }

            // Recarrega categorias se houver erro
            ViewBag.ListaCategorias = Persistencia.CarregarCategorias();
            return View(despesaAtualizada);
        }
    }
}

GestaoFinancas/GestaoFinancasWeb/Controllers/ReceitasController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using GestaoFinancasWeb.Models;
using Microsoft.AspNetCore.Http; 

namespace GestaoFinancasWeb.Controllers
{
    public class ReceitasController : Controller
    {
        private static List<Receita> listaReceitas = Persistencia.CarregarReceitas();

        // LISTAR
        public IActionResult Index()
        {
            // Segurança: Se não houver login, manda para fora
            if (HttpContext.Session.GetString("Utilizador") == null)
            {
                return RedirectToAction("Login", "Conta");
            }

            listaReceitas = Persistencia.CarregarReceitas();
            return View(listaReceitas);
        }

        // CRIAR (Formulário)
        public IActionResult Criar()
        {
          
            // Envia a lista de categorias para o Dropdown funcionar
            ViewBag.ListaCategorias = Persistencia.CarregarCategorias(); 
            return View();
        }

        // CRIAR (Guardar)
        [HttpPost]
        public IActionResult Criar(Receita novaReceita)
        {
            if (ModelState.IsValid)
            {
                novaReceita.Identificacao = listaReceitas.Count > 0 ? listaReceitas.Max(r => r.Identificacao) + 1 : 1;
                listaReceitas.Add(novaReceita);
                Persistencia.GuardarReceitas(listaReceitas); 
                return RedirectToAction("Index");
            }
            

            // Se der erro, recarrega a lista para o Dropdown não desaparecer
            ViewBag.ListaCategorias = Persistencia.CarregarCategorias();
            return View(novaReceita);
        }

        // ELIMINAR (Pergunta)
        public IActionResult Eliminar(int id)
        {
            var receita = listaReceitas.FirstOrDefault(r => r.Identificacao == id);
            if (receita == null) return NotFound();
            return View(receita);
        }

        // ELIMINAR (Confirmar)
        [HttpPost, ActionName("Eliminar")]
        public IActionResult ConfirmarEliminar(int id)
        {
            var receita = listaReceitas.FirstOrDefault(r => r.Identificacao == id);
            if (receita != null)
            {
                listaReceitas.Remove(receita);
                Persistencia.GuardarReceitas(listaReceitas); 
            }
            return RedirectToAction("Index");
        }

        // EDITAR (Formulário)
        public IActionResult Editar(int id)
        {
            var receita = listaReceitas.FirstOrDefault(r => r.Identificacao == id);
            if (receita == null) return NotFound();


            // No editar também precisamos do Dropdown
            ViewBag.ListaCategorias = Persistencia.CarregarCategorias();

            return View(receita);
        }

        // EDITAR (Guardar)
        [HttpPost]
        public IActionResult Editar(Receita receitaAtualizada)
        {
            var receitaAntiga = listaReceitas.FirstOrDefault(r => r.Identificacao == receitaAtualizada.Identificacao);
            if (receitaAntiga != null)
            {
                receitaAntiga.Descricao = receitaAtualizada.Descricao;
                receitaAntiga.Valor = receitaAtualizada.Valor;
                receitaAntiga.CategoriaNome = receitaAtualizada.CategoriaNome;
                receitaAntiga.Data = receitaAtualizada.Data;
                
                Persistencia.GuardarReceitas(listaReceitas); 
                return RedirectToAction("Index");
            }

            // Se der erro, isto recarrega a lista com o resturn
            ViewBag.ListaCategorias = Persistencia.CarregarCategorias();
            return View(receitaAtualizada);
        }
    }
}

GestaoFinancas/GestaoFinancasWeb/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - GestaoFinancasWeb</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/GestaoFinancasWeb.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Gestão Finanças</a>
                
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        
                        @if (Context.Session.GetString("Utilizador") != null)
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Home" asp-action="Index">Início</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Receitas" asp-action="Index">Receitas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Despesas" asp-action="Index">Despesas</a>
                            </li>
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Categorias" asp-action="Index">Categorias</a>
                            </li>
                        }
                    </ul>

                    <ul class="navbar-nav">
                        @if (Context.Session.GetString("Utilizador") != null)
                        {
                            <li class="nav-item">
                                <span class="nav-link text-secondary">Olá, <strong>@Context.Session.GetString("Utilizador")</strong></span>
                            </li>
                            <li class="nav-item">
                                <a class="btn btn-outline-danger btn-sm ms-2" asp-controller="Conta" asp-action="Logout">Sair</a>
                            </li>
                        }
                        else
                        {
                            <li class="nav-item">
                                <a class="nav-link text-dark" asp-controller="Conta" asp-action="Login">Login</a>
                            </li>
                        }
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - GestaoFinancasWeb - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>